DECLARE
  V_COUNT NUMBER;
BEGIN
  SELECT COUNT(*) INTO V_COUNT FROM ALL_TABLES
  WHERE TABLE_NAME = 'PM_USUARIO'
  AND OWNER = 'HALLANCHRISTIAN131';

  IF V_COUNT = 0 THEN
    EXECUTE IMMEDIATE 'CREATE TABLE PM_USUARIO (
                      ID NUMBER NOT NULL ENABLE,
                      NOME VARCHAR2(255),
                      PASSWORD VARCHAR2(4000),
                      TOKEN VARCHAR2(255),
                      CONSTRAINT USUARIO_PK PRIMARY KEY (ID) ENABLE
                      )';
  ELSE
    DBMS_OUTPUT.PUT_LINE('TABELA JA EXISTE !');
  END IF;
END;

/

DECLARE
V_COUNT INTEGER;
BEGIN
SELECT COUNT(*) INTO V_COUNT FROM USER_SEQUENCES
WHERE SEQUENCE_NAME = 'PM_USUARIO_SEQ';

IF V_COUNT = 0 THEN
EXECUTE IMMEDIATE
'CREATE SEQUENCE "PM_USUARIO_SEQ" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE';
ELSE
DBMS_OUTPUT.PUT_LINE('JÁ EXISTE A SEQUENCE PM_USUARIO_SEQ');
END IF;
END;
/

declare 
  l_count integer;
begin
  select count(*)
    into l_count
  from user_triggers
  where trigger_name = 'TRG_PM_USUARIO';

  if l_count > 0 then 
     execute immediate 'drop trigger TRG_PM_USUARIO';
  end if;

end;
/

CREATE trigger "TRG_PM_USUARIO"
  before insert on "PM_USUARIO"
  for each row
begin
  if :NEW."ID" is null then
    select "PM_USUARIO_SEQ".nextval into :NEW."ID" from sys.dual;
  end if;
end;
/
ALTER TRIGGER  "TRG_PM_USUARIO" ENABLE;
/
DECLARE
  V_COUNT NUMBER;
BEGIN
  SELECT COUNT(*) INTO V_COUNT FROM ALL_TABLES
  WHERE TABLE_NAME = 'PM_PAGINA'
  AND OWNER = 'HALLANCHRISTIAN131';

  IF V_COUNT = 0 THEN
    EXECUTE IMMEDIATE 'CREATE TABLE PM_PAGINA (
                      ID NUMBER NOT NULL ENABLE,
                      NOME VARCHAR2(255),
                      APEX_APP_ID NUMBER,
                      APEX_PAGE_ID NUMBER,
                      CONSTRAINT PM_PAGINA_PK PRIMARY KEY (ID) ENABLE
                      )';
  ELSE
    DBMS_OUTPUT.PUT_LINE('TABELA JA EXISTE !');
  END IF;
END;

/

DECLARE
V_COUNT INTEGER;
BEGIN
SELECT COUNT(*) INTO V_COUNT FROM USER_SEQUENCES
WHERE SEQUENCE_NAME = 'PM_PAGINA_SEQ';

IF V_COUNT = 0 THEN
EXECUTE IMMEDIATE
'CREATE SEQUENCE "PM_PAGINA_SEQ" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE';
ELSE
DBMS_OUTPUT.PUT_LINE('JÁ EXISTE A SEQUENCE PM_PAGINA_SEQ');
END IF;
END;
/

declare 
  l_count integer;
begin
  select count(*)
    into l_count
  from user_triggers
  where trigger_name = 'TRG_PM_PAGINA';

  if l_count > 0 then 
     execute immediate 'drop trigger TRG_PM_PAGINA';
  end if;

end;
/

CREATE trigger "TRG_PM_PAGINA"
  before insert on "PM_PAGINA"
  for each row
begin
  if :NEW."ID" is null then
    select "PM_PAGINA_SEQ".nextval into :NEW."ID" from sys.dual;
  end if;
end;
/
ALTER TRIGGER  "TRG_PM_PAGINA" ENABLE;
/

DECLARE
  V_COUNT NUMBER;
BEGIN
  SELECT COUNT(*) INTO V_COUNT FROM ALL_TABLES
  WHERE TABLE_NAME = 'PM_ROLE'
  AND OWNER = 'HALLANCHRISTIAN131';

  IF V_COUNT = 0 THEN
    EXECUTE IMMEDIATE 'CREATE TABLE PM_ROLE (
                      ID NUMBER NOT NULL ENABLE,
                      NOME VARCHAR2(255),
                      APEX_PAGES VARCHAR2(4000),
                      CONSTRAINT PM_ROLE_PK PRIMARY KEY (ID) ENABLE
                      )';
  ELSE
    DBMS_OUTPUT.PUT_LINE('TABELA JA EXISTE !');
  END IF;
END;

/

DECLARE
V_COUNT INTEGER;
BEGIN
SELECT COUNT(*) INTO V_COUNT FROM USER_SEQUENCES
WHERE SEQUENCE_NAME = 'PM_ROLE_SEQ';

IF V_COUNT = 0 THEN
EXECUTE IMMEDIATE
'CREATE SEQUENCE "PM_ROLE_SEQ" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE';
ELSE
DBMS_OUTPUT.PUT_LINE('JÁ EXISTE A SEQUENCE PM_ROLE_SEQ');
END IF;
END;
/

declare 
  l_count integer;
begin
  select count(*)
    into l_count
  from user_triggers
  where trigger_name = 'TRG_PM_ROLE';

  if l_count > 0 then 
     execute immediate 'drop trigger TRG_PM_ROLE';
  end if;

end;
/

CREATE trigger "TRG_PM_ROLE"
  before insert on "PM_ROLE"
  for each row
begin
  if :NEW."ID" is null then
    select "PM_ROLE_SEQ".nextval into :NEW."ID" from sys.dual;
  end if;
end;
/
ALTER TRIGGER  "TRG_PM_ROLE" ENABLE;
/

DECLARE
  V_COUNT NUMBER;
BEGIN
  SELECT COUNT(*) INTO V_COUNT FROM ALL_TABLES
  WHERE TABLE_NAME = 'PM_GRUPO'
  AND OWNER = 'HALLANCHRISTIAN131';

  IF V_COUNT = 0 THEN
    EXECUTE IMMEDIATE 'CREATE TABLE PM_GRUPO (
                      ID NUMBER NOT NULL ENABLE,
                      NOME VARCHAR2(255),
                      ROLES VARCHAR2(4000),
                      CONSTRAINT PM_GRUPO_PK PRIMARY KEY (ID) ENABLE
                      )';
  ELSE
    DBMS_OUTPUT.PUT_LINE('TABELA JA EXISTE !');
  END IF;
END;

/

DECLARE
V_COUNT INTEGER;
BEGIN
SELECT COUNT(*) INTO V_COUNT FROM USER_SEQUENCES
WHERE SEQUENCE_NAME = 'PM_GRUPO_SEQ';

IF V_COUNT = 0 THEN
EXECUTE IMMEDIATE
'CREATE SEQUENCE "PM_GRUPO_SEQ" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE';
ELSE
DBMS_OUTPUT.PUT_LINE('JÁ EXISTE A SEQUENCE PM_GRUPO_SEQ');
END IF;
END;
/

declare 
  l_count integer;
begin
  select count(*)
    into l_count
  from user_triggers
  where trigger_name = 'TRG_PM_GRUPO';

  if l_count > 0 then 
     execute immediate 'drop trigger TRG_PM_GRUPO';
  end if;

end;
/

CREATE trigger "TRG_PM_GRUPO"
  before insert on "PM_GRUPO"
  for each row
begin
  if :NEW."ID" is null then
    select "PM_GRUPO_SEQ".nextval into :NEW."ID" from sys.dual;
  end if;
end;
/
ALTER TRIGGER  "TRG_PM_GRUPO" ENABLE;
/

DECLARE
  V_COUNT NUMBER;
BEGIN
  SELECT COUNT(*) INTO V_COUNT FROM ALL_TABLES
  WHERE TABLE_NAME = 'PM_GRUPO_USUARIO'
  AND OWNER = 'HALLANCHRISTIAN131';

  IF V_COUNT = 0 THEN
    EXECUTE IMMEDIATE 'CREATE TABLE PM_GRUPO_USUARIO (
                      ID NUMBER NOT NULL ENABLE,
                      PM_USUARIO_ID NUMBER,
                      PM_GRUPO_ID NUMBER,
                      CONSTRAINT PM_GRUPO_USUARIO_PK PRIMARY KEY (ID) ENABLE
                      )';
  ELSE
    DBMS_OUTPUT.PUT_LINE('TABELA JA EXISTE !');
  END IF;
END;

/
DECLARE
  V_COUNT INTEGER;
BEGIN
    SELECT COUNT(*) INTO V_COUNT FROM USER_CONSTRAINTS
    WHERE CONSTRAINT_NAME = 'PM_GRUPO_USUARIO_FK_PM_USUARIO';

    IF V_COUNT = 0 THEN
      EXECUTE IMMEDIATE
      'ALTER TABLE PM_GRUPO_USUARIO ADD CONSTRAINT "PM_GRUPO_USUARIO_FK_PM_USUARIO" FOREIGN KEY (PM_USUARIO_ID)
      REFERENCES  PM_USUARIO (ID) ENABLE';
  ELSE
      DBMS_OUTPUT.PUT_LINE('A FOREIGN KEY PM_GRUPO_USUARIO_FK_PM_USUARIO JÁ EXISTE.');
  END IF;
END;
/


DECLARE V_COUNT_IDX INTEGER;
BEGIN
    SELECT COUNT(*) INTO V_COUNT_IDX FROM USER_INDEXES
    WHERE INDEX_NAME = 'PM_GRUPO_USUARIO_IDX_PM_USUARIO'
    AND TABLE_NAME = 'PM_GRUPO_USUARIO';

    IF V_COUNT_IDX = 0 THEN
        EXECUTE IMMEDIATE
        'CREATE INDEX  "PM_GRUPO_USUARIO_IDX_PM_USUARIO" ON  "PM_GRUPO_USUARIO" ("PM_USUARIO_ID")';
    ELSE
        DBMS_OUTPUT.PUT_LINE('JÁ EXISTE O PM_GRUPO_USUARIO_IDX_PM_USUARIO ');
    END IF;
END;
/
DECLARE
  V_COUNT INTEGER;
BEGIN
    SELECT COUNT(*) INTO V_COUNT FROM USER_CONSTRAINTS
    WHERE CONSTRAINT_NAME = 'PM_GRUPO_USUARIO_FK_PM_GRUPO';

    IF V_COUNT = 0 THEN
      EXECUTE IMMEDIATE
      'ALTER TABLE PM_GRUPO_USUARIO ADD CONSTRAINT "PM_GRUPO_USUARIO_FK_PM_GRUPO" FOREIGN KEY (PM_GRUPO_ID)
      REFERENCES PM_GRUPO (ID) ENABLE';
  ELSE
      DBMS_OUTPUT.PUT_LINE('A FOREIGN KEY PM_GRUPO_USUARIO_FK_PM_GRUPO JÁ EXISTE.');
  END IF;
END;
/

DECLARE V_COUNT_IDX INTEGER;
BEGIN
    SELECT COUNT(*) INTO V_COUNT_IDX FROM USER_INDEXES
    WHERE INDEX_NAME = 'PM_GRUPO_USUARIO_IDX_PM_GRUPO'
    AND TABLE_NAME = 'PM_GRUPO_USUARIO';

    IF V_COUNT_IDX = 0 THEN
        EXECUTE IMMEDIATE
        'CREATE INDEX  "PM_GRUPO_USUARIO_IDX_PM_GRUPO" ON  "PM_GRUPO_USUARIO" ("PM_GRUPO_ID")';
    ELSE
        DBMS_OUTPUT.PUT_LINE('JÁ EXISTE O PM_GRUPO_USUARIO_IDX_PM_GRUPO ');
    END IF;
END;
/
DECLARE
V_COUNT INTEGER;
BEGIN
SELECT COUNT(*) INTO V_COUNT FROM USER_SEQUENCES
WHERE SEQUENCE_NAME = 'PM_GRUPO_USUARIO_SEQ';

IF V_COUNT = 0 THEN
EXECUTE IMMEDIATE
'CREATE SEQUENCE "PM_GRUPO_USUARIO_SEQ" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE';
ELSE
DBMS_OUTPUT.PUT_LINE('JÁ EXISTE A SEQUENCE PM_GRUPO_USUARIO_SEQ');
END IF;
END;
/

declare 
  l_count integer;
begin
  select count(*)
    into l_count
  from user_triggers
  where trigger_name = 'TRG_PM_GRUPO_USUARIO';

  if l_count > 0 then 
     execute immediate 'drop trigger PM_GRUPO_USUARIO';
  end if;

end;
/

CREATE trigger "TRG_PM_GRUPO_USUARIO"
  before insert on "PM_GRUPO_USUARIO"
  for each row
begin
  if :NEW."ID" is null then
    select "PM_GRUPO_USUARIO_SEQ".nextval into :NEW."ID" from sys.dual;
  end if;
end;
/
ALTER TRIGGER  "TRG_PM_GRUPO_USUARIO" ENABLE;
/
